### ISSUE TITLE
Adapter getting Token but then errors

### ISSUE THREAD

**Issue by reutli** [ice987987/ioBroker.husqvarna-automower#11]
Adapter is starting, is getting Token, but then errors:

`

husqvarna-automower.0 | 2022-04-18 07:50:59.829 | error | "Automower Connect API" not reachable. Please check "Username, "Password and/or "API Key". (ERR_#008)
-- | -- | -- | --
husqvarna-automower.0 | 2022-04-18 07:50:59.829 | error | Error: "Automower Connect API" not reachable. Please check "Username, "Password and/or "API Key". (ERR_#008) at /usr/local/iobroker/node_modules/iobroker.husqvarna-automower/main.js:154:11 at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5) at async HusqvarnaAutomower.getRefreshToken (/usr/local/iobroker/node_modules/iobroker.husqvarna-automower/main.js:125:3)
husqvarna-automower.0 | 2022-04-18 07:50:59.829 | error | unhandled promise rejection: "Automower Connect API" not reachable. Please check "Username, "Password and/or "API Key". (ERR_#008)
husqvarna-automower.0 | 2022-04-18 07:50:59.828 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
husqvarna-automower.0 | 2022-04-18 07:50:59.342 | info | System information saved...
husqvarna-automower.0 | 2022-04-18 07:50:58.930 | info | "Husqvarna Authentication API Access token" received.
husqvarna-automower.0 | 2022-04-18 07:50:58.659 | info | Trying to connect "Automower Connect API"...
husqvarna-automower.0 | 2022-04-18 07:50:58.657 | info | starting adapter "husqvarna-automower"...
husqvarna-automower.0 | 2022-04-18 07:50:58.653 | info | starting. Version 0.0.4 (non-npm: ice987987/ioBroker.husqvarna-automower#c824ffaf8c69e785bada1b4dbce1ed34752bdd3c) in /usr/local/iobroker/node_modules/iobroker.husqvarna-automower, node: v14.15.3, js-controller: 4.0.21

`
credentials and API Key are connected to APIs.

**Comment by reutli** [comment]
DONE: Requested complete new API & API Key. Inserted that - works.
